apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: app   # use "default" if you don’t have a db namespace
type: Opaque
stringData:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin123
  POSTGRES_DB: postgresdb
