apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: app
  labels:
    app: kube-master
spec:
  ports:
    - port: 5432
      name: postgres
  clusterIP: None
  selector:
    app: kube-master